// adaptors/solid-sxo/src/components/Button.tsx
import { type ButtonOptions, getButtonClasses } from '@sxo/ui';
import { type JSX, splitProps } from 'solid-js';

export type ButtonProps = ButtonOptions & JSX.ButtonHTMLAttributes<HTMLButtonElement>;

export function Button(props: ButtonProps) {
    const [local, others] = splitProps(props, ['variant', 'size', 'rounded', 'class']);

    const classes = () => {
        const sxoClasses = getButtonClasses({
            variant: local.variant,
            size: local.size,
            rounded: local.rounded,
        });
        return `${sxoClasses} ${local.class || ''}`.trim();
    };

    return (
        <button {...others} class={classes()}>
            {props.children}
        </button>
    );
}

// adaptors/react-sxo/src/components/Button.tsx
import { type ButtonOptions, getButtonClasses } from '@sxo/ui';
import React from 'react';
import { useStyle } from '../hooks.ts';

export interface ButtonProps extends ButtonOptions, React.ButtonHTMLAttributes<HTMLButtonElement> {
    children?: React.ReactNode;
}

export const Button: React.FC<ButtonProps> = ({
    variant,
    size,
    disabled,
    rounded,
    className,
    children,
    ...props
}) => {
    const sxoClasses = getButtonClasses({ variant, size, disabled, rounded });
    const finalClasses = useStyle(`${sxoClasses} ${className || ''}`);

    return React.createElement(
        'button',
        {
            className: finalClasses,
            disabled,
            ...props,
        },
        children,
    );
};
