// adaptors/solid-sxo/src/components/Input.tsx
import { getInputClasses, type InputOptions } from '@sxo/ui';
import { type JSX, splitProps } from 'solid-js';

export type InputProps = InputOptions & Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'size'>;

export function Input(props: InputProps) {
    const [local, others] = splitProps(props, ['variant', 'size', 'class']);

    const classes = () => {
        const sxoClasses = getInputClasses({
            variant: local.variant,
            size: local.size,
        });
        return `${sxoClasses} ${local.class || ''}`.trim();
    };

    return <input {...others} class={classes()} />;
}

// adaptors/react-sxo/src/components/Input.tsx
import { getInputClasses, type InputOptions } from '@sxo/ui';
import type React from 'react';
import { useStyle } from '../hooks.ts';

export interface InputProps
    extends InputOptions,
        Omit<React.InputHTMLAttributes<HTMLInputElement>, 'size'> {}

export const Input: React.FC<InputProps> = ({
    variant = 'outline',
    size = 'md',
    invalid = false,
    className = '',
    ...props
}) => {
    const sxoClasses = getInputClasses({ variant, size, invalid });
    const combinedClasses = useStyle(`${sxoClasses} ${className}`.trim());

    return <input className={combinedClasses} {...props} />;
};
