// adaptors/solid-sxo/src/components/Tag.tsx
import { getTagClasses, type TagOptions } from '@sxo/ui';
import { type JSX, splitProps } from 'solid-js';

export type TagProps = TagOptions & JSX.HTMLAttributes<HTMLSpanElement>;

export function Tag(props: TagProps) {
    const [local, others] = splitProps(props, ['variant', 'color', 'rounded', 'class']);

    const classes = () => {
        const sxoClasses = getTagClasses({
            variant: local.variant,
            color: local.color,
            rounded: local.rounded,
        });
        return `${sxoClasses.base} ${local.class || ''}`.trim();
    };

    return (
        <span {...others} class={classes()}>
            {props.children}
        </span>
    );
}

// adaptors/react-sxo/src/components/Tag.tsx
import { getTagClasses, type TagOptions } from '@sxo/ui';
import type React from 'react';
import { useStyle } from '../hooks.ts';

export interface TagProps extends TagOptions, React.HTMLAttributes<HTMLSpanElement> {
    children?: React.ReactNode;
    onClose?: () => void;
}

export const Tag: React.FC<TagProps> = ({
    variant = 'solid',
    color = 'primary',
    rounded = 'sm',
    size = 'md',
    closable = false,
    className = '',
    children,
    onClose,
    ...props
}) => {
    const sxoClasses = getTagClasses({ variant, color, rounded, size, closable });
    const finalClasses = useStyle(`${sxoClasses.base} ${className}`.trim());

    return (
        <span className={finalClasses} {...props}>
            {children}
            {closable && (
                <span
                    className={sxoClasses.closeIcon}
                    onClick={(e) => {
                        e.stopPropagation();
                        onClose?.();
                    }}
                >
                    ×
                </span>
            )}
        </span>
    );
};
